script "com.fmpromigrator.widget.buttonbar.__DefaultScript"
-- Sent when a button is clicked
--
on buttonClicked pButtonName
   -- branch based upon name of clicked button
   switch pButtonName
      case "first"
         break
      case "previous"
         break
      case "next"
         break
      case "last"
         break
      default
         -- do nothing if empty
   end switch
end buttonClicked
